# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "nunitr"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Robert Beal"]
  s.date = "2012-08-16"
  s.description = "Find and tokenise files!"
  s.email = "rob.beal@7digital.com"
  s.files = [
    "lib/nunitr.rb",
    "lib/nunitr/nunit.rb"
  ]
  s.homepage = "https://github.com/7digital/NUnitr"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Build tasks for .Net projects"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, ["= 0.9.2.2"])
      s.add_development_dependency(%q<rspec>, ["= 2.9.0"])
      s.add_development_dependency(%q<mocha>, ["= 0.10.5"])
      s.add_development_dependency(%q<rdoc>, ["= 3.12"])
      s.add_development_dependency(%q<jeweler>, ["= 1.8.3"])
    else
      s.add_dependency(%q<rake>, ["= 0.9.2.2"])
      s.add_dependency(%q<rspec>, ["= 2.9.0"])
      s.add_dependency(%q<mocha>, ["= 0.10.5"])
      s.add_dependency(%q<rdoc>, ["= 3.12"])
      s.add_dependency(%q<jeweler>, ["= 1.8.3"])
    end
  else
    s.add_dependency(%q<rake>, ["= 0.9.2.2"])
    s.add_dependency(%q<rspec>, ["= 2.9.0"])
    s.add_dependency(%q<mocha>, ["= 0.10.5"])
    s.add_dependency(%q<rdoc>, ["= 3.12"])
    s.add_dependency(%q<jeweler>, ["= 1.8.3"])
  end
end

